---
# tasks file for fffm_common

- name: update package index - apt
  apt: update_cache=yes
  tags: long-tasks
  when: ansible_os_family == "Debian"

- name: install packages - RedHat
  yum:
    name: "{{ fffm_common_packages_redhat }}"
    state: present
  when: ansible_os_family == "RedHat"
- name: install common packages - Debian
  apt:
    name: "{{ fffm_common_packages_debian }}"
  when: ansible_os_family == "Debian"
- name: place user tmux configuration
  copy:
    src: tmux.conf
    dest: "/home/{{ item }}/.tmux.conf"
    owner: "{{ item }}"
    group: "domain users"
    mode: 0644
  when: item != "root"
  with_items: "{{ fffm_tmux_users }}"

- name: place root tmux configuration
  copy:
    src: tmux.conf
    dest: "/{{ item }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
  when: item == "root"
  with_items: "{{ fffm_tmux_users }}"

  
